In [1]:
from sklearn.datasets import load_iris
from sklearn import tree
import numpy as np
from sklearn.model_selection import train_test_split


In [2]:
iris=load_iris()

In [19]:
iris.data[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

In [20]:
iris.target[:5]

array([0, 0, 0, 0, 0])

In [22]:
np.unique(iris.target)

array([0, 1, 2])

In [23]:
iris.target.__len__()

150

In [24]:
dt=tree.DecisionTreeClassifier()

In [25]:
trainX, testX, trainY,testY=train_test_split(iris.data, iris.target)

In [26]:
print (trainX.__len__())
print (testX.__len__())

112
38


In [27]:
dt.fit(trainX, trainY)
dt.score(testX, testY)

1.0

In [28]:
dt.fit(testX, testY)
dt.score(trainX, trainY)

0.9375

In [31]:
dt.fit(trainX, trainY)
dt.predict(testX[:10])

array([2, 2, 0, 0, 2, 2, 2, 0, 0, 1])

In [32]:
testY[:10]

array([2, 2, 0, 0, 2, 2, 2, 0, 0, 1])